name: aurore_mobile_flutter
description: "UI coding challenge"

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK version compatibility
environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^3.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets declaration
  assets:
    - assets/google.png
    - assets/pinterest.png
    - assets/office.jpg
